kartAI/NGIS-training-machine-webclient

- frontend/pages/map.html
- frontend/scripts/map.js
La til en søkefunksjon i Leaflet kartet, nå kan man søke på hvor enn i verden hvis man ønsker dette. Endret også på startpunktet da kartet initialiserer, så man ikke er cursed med å stirre på sandvika storsenter.
> Søkefunksjon og endring av posisjon

- WMS/Sanderscript.py
Lagt inn sander sitt script, fungerer som den skal.
> Sanderscript

- frontend/scripts/upload.js
> Minifiks for path i fastAPI uptadewmscoordinates

- test_main.py
> gjenopprettet test

- COG_FGB/getCog.py
Enda ikke funnet ut hvordan man kan lese/hente tiff/png fra blob, men her er skjellettet til connection
> Folder + azure blob connection

- COG_FGB/getCog.py
- requirements.txt
La til at kartet blir generert og fargelagt
> Azureblobstorageconnection

- frontend/scripts/map.js
meget komplisert fix for radius på markørene
> meget komplisert fix for radius på markørene

- frontend/scripts/order.js
> Header på order

- application/labelPhotoWMS.py
- application/ortoCOG.py
- application/util.py
- frontend/scripts/coordinates.js
- frontend/scripts/home.js
- frontend/scripts/map.js
- frontend/scripts/methods.js
- frontend/scripts/order.js
- frontend/scripts/script.js
- frontend/scripts/upload.js
> dokumentasjon på kode

- test_main.py
> testopprettingv2

- frontend/pages/methods.html
- frontend/scripts/methods.js
Legge til load ikon før tilbakemelding i valg av ortofoto og label source for å tydeliggjøre til brukeren at input er oppdatert.
> legge til load ikon på methodssiden

- frontend/pages/setConstraints.html
> constrainstinfo

- application/ortoCOG.py
- application/ortoPhotoWMS.py
- main.py
Pathsa til env filen er endret, ligger ikke lenger i ngisopenapi men i application
> endret paths til env fil

- frontend/pages/home.html
> oppdatert home

- application/satWMS.py
> satelittfunker

- frontend/pages/info.html
- frontend/scripts/info.js
- frontend/style.css
Lagt til GDPR til info.html og fikset litt på pop-upsene.
> GDPR til info.html

- frontend/pages/info.html
> Mer info på info-sida

- frontend/pages/coordinates.html
- frontend/pages/methods.html
- frontend/pages/uploadFile.html
legge til info Popup modal for html-sidene uploadFile, coordinates og methods
> legge til info popup 

- main.py
- test_main.py
test av datagenerasjon + fjerning av sendgrid imports og liten fix i main SAT kall
> datakildeteste

- frontend/pages/map.html
- frontend/pages/methods.html
- frontend/pages/setConstraints.html
*Fikset engelsk
*Fikset disclosed areas knappen
*Endret overskriften på constraints til settings
> Fikset engelsk på methods, sjekket også resten av sidene 

- frontend/pages/home.html
- frontend/pages/info.html
- frontend/pages/methods.html
- frontend/pages/setConstraints.html
- frontend/style.css
endret overskrift til "Define Application settings" for nå. Kan høre med Sander hva som er mest riktig.
> Midlertidig endring av overskriften i constraints-siden

- frontend/style.css
justerte størrelsen av tooltip boksene og teksten for å gjøre det med leselig
> Adjust tooltip size

- frontend/pages/header.html
- frontend/pages/info.html
- frontend/pages/order.html
Order siden vil ikke laste inn for meg så jeg ser ikke om info knappen har blitt fjernet derfra, men gjorde det samme som på home.html. Dere får sjekke.
> Fjerne info knappen fra header i order.html og home.html ettersom den ikke trengs.
